[package]
name = "pg-trunk"
version = "0.0.1-alpha.1"
edition = "2021"
authors = ["Steven Miller"]
description = "A package manager for PostgreSQL extensions"
homepage = "https://trnk.io"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/coredb-io/trunk"

[[bin]]
name = "trunk"
path = "src/main.rs"

[dependencies]
bollard = "0.14.0"
clap = { version = "4.1.1", features = ["derive"] }
serde_json = "1.0.91"
serde_yaml = "0.9.17"
tar = "0.4.38"
thiserror = "1.0.38"
toml = "0.7.2"

[dev-dependencies]
assert_cmd = "2.0.8"
predicates = "2.1.5"
