name: PGX builder images

on:
  pull_request:
    paths:
    - '.github/workflows/images.yaml'
    - 'images/pgx-builder/**'
  push:
    branches:
      - 'main'

jobs:
  build_and_push_images:
    name: Build and push images
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        pg_version:
          - "15"
          - "14"
        pgx_version:
          - "0.7.1"
          - "0.7.2"
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          pull: true
          push: true
          tags: quay.io/coredb/pgx-builder:pg${{ matrix.pg_version }}-pgx${{ matrix.pgx_version }}
          platforms: linux/amd64,linux/arm64
          context: images/pgx-builder
          build-args: |
            PG_VERSION=${{ matrix.pg_version }}
            PGX_VERSION=${{ matrix.pgx_version }}
